{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.rly_sdk",
    "module": "flutter_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-f40e976bedff57e69e1b3d89a7c2a3c617a03dad"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-f40e976bedff57e69e1b3d89a7c2a3c617a03dad"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-f40e976bedff57e69e1b3d89a7c2a3c617a03dad"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-f40e976bedff57e69e1b3d89a7c2a3c617a03dad"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.rly_network.rly_network_flutter_sdk",
          "module": "rly_network_flutter_sdk_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.0.aar",
          "url": "flutter_profile-1.0.aar",
          "size": 5289886,
          "sha512": "8ad8fb4d37d00a18bb56168c9058518023e3c024939f20e261de5a565538c25dd36074fee032c4d81f83fd1135e13c88270f55a6a5d6463bb6afbe768a5e80a9",
          "sha256": "60ff149c0855422bf727fd51dcd1f749eab10110063d74a6efeb7d62e3c2f0c0",
          "sha1": "e10fa09c462dbf5152bcdb73d765c88f5a25d1a3",
          "md5": "5e982c589a047195bb15d3da22eb9cb6"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-f40e976bedff57e69e1b3d89a7c2a3c617a03dad"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-f40e976bedff57e69e1b3d89a7c2a3c617a03dad"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-f40e976bedff57e69e1b3d89a7c2a3c617a03dad"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-f40e976bedff57e69e1b3d89a7c2a3c617a03dad"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.rly_network.rly_network_flutter_sdk",
          "module": "rly_network_flutter_sdk_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.0.aar",
          "url": "flutter_profile-1.0.aar",
          "size": 5289886,
          "sha512": "8ad8fb4d37d00a18bb56168c9058518023e3c024939f20e261de5a565538c25dd36074fee032c4d81f83fd1135e13c88270f55a6a5d6463bb6afbe768a5e80a9",
          "sha256": "60ff149c0855422bf727fd51dcd1f749eab10110063d74a6efeb7d62e3c2f0c0",
          "sha1": "e10fa09c462dbf5152bcdb73d765c88f5a25d1a3",
          "md5": "5e982c589a047195bb15d3da22eb9cb6"
        }
      ]
    }
  ]
}
