{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.rly_sdk",
    "module": "flutter_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-f40e976bedff57e69e1b3d89a7c2a3c617a03dad"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-f40e976bedff57e69e1b3d89a7c2a3c617a03dad"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-f40e976bedff57e69e1b3d89a7c2a3c617a03dad"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-f40e976bedff57e69e1b3d89a7c2a3c617a03dad"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.rly_network.rly_network_flutter_sdk",
          "module": "rly_network_flutter_sdk_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 3267509,
          "sha512": "bb7c18edba6d13407d7325f27818ec10e06ec185c8d0e710469bace2b5f9cacfaec9bb033c65e7401356de9d767a9e128e27efc21e55eb87971063035ab9bf76",
          "sha256": "2d2ad4b82be09848f230ad3f67cd67ac20e5a4dd06a92baf56bcd33a4d3139d3",
          "sha1": "682ec42100de36181089f8f0535e0f823478e926",
          "md5": "3157313e5df53bbeb45d5bb4df7ae7af"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-f40e976bedff57e69e1b3d89a7c2a3c617a03dad"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-f40e976bedff57e69e1b3d89a7c2a3c617a03dad"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-f40e976bedff57e69e1b3d89a7c2a3c617a03dad"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-f40e976bedff57e69e1b3d89a7c2a3c617a03dad"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.rly_network.rly_network_flutter_sdk",
          "module": "rly_network_flutter_sdk_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 3267509,
          "sha512": "bb7c18edba6d13407d7325f27818ec10e06ec185c8d0e710469bace2b5f9cacfaec9bb033c65e7401356de9d767a9e128e27efc21e55eb87971063035ab9bf76",
          "sha256": "2d2ad4b82be09848f230ad3f67cd67ac20e5a4dd06a92baf56bcd33a4d3139d3",
          "sha1": "682ec42100de36181089f8f0535e0f823478e926",
          "md5": "3157313e5df53bbeb45d5bb4df7ae7af"
        }
      ]
    }
  ]
}
